CFLAGS += -Isrc/bdwgc/libatomic_ops \
	-Isrc/bdwgc/libatomic_ops/atomic_ops \
	-Isrc/bdwgc/libatomic_ops/atomic_ops/sysdeps \
	-Isrc/bdwgc/libatomic_ops/atomic_ops/sysdeps/gcc
obj-y += atomic_ops.o 

